In [1]:
import torch

## 创建tensor

In [8]:
x = torch.arange(12)
x.reshape(4, -1)

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])

In [9]:
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [10]:
torch.ones((2, 3, 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [11]:
torch.randn(3, 4)

tensor([[ 0.0733, -1.8011, -0.2322,  0.7712],
        [ 1.6356, -1.1141, -0.4197, -1.0951],
        [-0.5945, -0.2305,  0.1985, -0.1718]])

In [12]:
torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

## 运算

In [13]:
x = torch.arange(10)
y = torch.arange(10)
x * y

tensor([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [14]:
torch.exp(x)

tensor([1.0000e+00, 2.7183e+00, 7.3891e+00, 2.0086e+01, 5.4598e+01, 1.4841e+02,
        4.0343e+02, 1.0966e+03, 2.9810e+03, 8.1031e+03])

In [16]:
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((X, Y), dim=0)
torch.cat((X, Y), dim=1)

tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]])

In [17]:
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

## 广播机制

In [6]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [19]:
a * b

tensor([[0, 0],
        [0, 1],
        [0, 2]])

## 索引和切片

In [3]:
X = torch.arange(20).reshape(5, -1)

In [4]:
X[-1]

tensor([16, 17, 18, 19])

In [5]:
X[:, 1] = 12
X

tensor([[ 0, 12,  2,  3],
        [ 4, 12,  6,  7],
        [ 8, 12, 10, 11],
        [12, 12, 14, 15],
        [16, 12, 18, 19]])

In [6]:
## 节省内存

In [7]:
X = torch.arange(20).reshape(5, -1)
id(X)

126830807358496

In [8]:
X[:, 1] = 12
X
id(X)

126830807358496

In [12]:
int(X[1, 2])

6

In [ ]:
import torch
a = torch.randn(2, 3)
type(a[0, 1].item())

float

In [11]:
a = torch.randn(2, 3)
len(a[1, :])

3

In [12]:
a[1, :]

tensor([-2.7067,  0.9351, -0.7477])