In [2]:
import torch

## 张量

In [3]:
B = torch.tensor([[1, 2, 3], [2, 0, 4], [3, 4, 5]])
B

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])

In [4]:
B.T

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])

In [5]:
B + 2

tensor([[3, 4, 5],
        [4, 2, 6],
        [5, 6, 7]])

In [8]:
A = torch.arange(9).reshape(3, -1)
A

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [9]:
B * A

tensor([[ 0,  2,  6],
        [ 6,  0, 20],
        [18, 28, 40]])

## 降维度

In [12]:
x = torch.arange(4, dtype=torch.float32)
x, x.sum()

(tensor([0., 1., 2., 3.]), tensor(6.))

In [15]:
A = torch.arange(30).reshape(5, 2, 3)
A, A.sum(axis=(0, 2), keepdim=True)

(tensor([[[ 0,  1,  2],
          [ 3,  4,  5]],
 
         [[ 6,  7,  8],
          [ 9, 10, 11]],
 
         [[12, 13, 14],
          [15, 16, 17]],
 
         [[18, 19, 20],
          [21, 22, 23]],
 
         [[24, 25, 26],
          [27, 28, 29]]]),
 tensor([[[195],
          [240]]]))

In [12]:
# 求和后广播
A = torch.arange(30).reshape(5, -1)
sum = A.sum(axis=0, keepdim=True)
A / sum

tensor([[0.0000, 0.0154, 0.0286, 0.0400, 0.0500, 0.0588],
        [0.1000, 0.1077, 0.1143, 0.1200, 0.1250, 0.1294],
        [0.2000, 0.2000, 0.2000, 0.2000, 0.2000, 0.2000],
        [0.3000, 0.2923, 0.2857, 0.2800, 0.2750, 0.2706],
        [0.4000, 0.3846, 0.3714, 0.3600, 0.3500, 0.3412]])

In [32]:
## dot product
y = torch.ones(4, dtype = torch.float32)
x, y, torch.dot(x, y)

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.))

In [35]:
## 矩阵向量积
A = torch.arange(20).reshape(5, 4)
x = torch.arange(4)
torch.mv(A, x)

tensor([ 14,  38,  62,  86, 110])

In [36]:
## 矩阵乘法
A = torch.ones(4, 3)
B = A.T
torch.mm(A, B)

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

In [ ]:
## 向量的范数
u = torch.tensor([3, -4.0])
# L2, F norm
torch.norm(u)
# L1
torch.abs(u).sum()

tensor(7.)

In [39]:
X = torch.arange(30).reshape(3, 2, -1)
len(X)

3