In [1]:
import torch

## 简单

In [6]:
## autograd
x = torch.tensor([1., 2., 3., 4.])
x.requires_grad_(True)
x.grad

In [7]:
y = 2 * torch.dot(x, x)
y.backward()
x.grad

tensor([ 4.,  8., 12., 16.])

In [9]:
x.grad == 4 * x

tensor([True, True, True, True])

## 非标量反向传播

In [2]:
x = torch.tensor([1., 2., 3., 4.])
x.requires_grad_(True)
y = x * x

In [3]:
y.sum().backward()

In [4]:
x.grad

tensor([2., 4., 6., 8.])

In [7]:
x = torch.tensor([1., 2., 3., 4.])
x.requires_grad_(True)
y = x * x
y.backward(torch.ones(len(x)))

In [8]:
x.grad

tensor([2., 4., 6., 8.])

In [9]:
## 分离计算
x = torch.tensor([1., 2., 3., 4.])
x.requires_grad_(True)
y = x * x
u = y.detach()
z = u * x
z.sum().backward()
x.grad

tensor([ 1.,  4.,  9., 16.])

In [11]:
x.grad.zero_()
y.sum().backward()
x.grad

tensor([2., 4., 6., 8.])

In [17]:
## 控制流梯度
def f(a):
    b = a * 2
    while b.norm() < 1000:
        b = b * 2
    if b.sum() > 0:
        c = b
    else:
        c = 100 * b
    return c

a = torch.randn(size=(), requires_grad=True)
d = f(a)
d.backward()
a.grad

tensor(2048.)

In [15]:
d / a

tensor(2048., grad_fn=<DivBackward0>)